#!/bin/bash -e

MACHINE=${MACHINE:-imx8mp-lpddr4-evk}
DISTRO=${DISTRO:-fsl-imx-xwayland}
EULA=1
T="../sources/meta-imx8mp-isp-imx219/bbfile"

. imx-setup-release.sh $@

for _d in ${T}/*;do
	_file=$(basename ${_d})
	for _f in ${_d}/*;do
		cat ${_f} >> conf/${_file}
	done;
done
